<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Set featured image</name>
   <tag></tag>
   <elementGuidId>45cd66fa-52a8-48f6-b20e-2549d8f8bf0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#set-post-thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='set-post-thumbnail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>113b421f-4159-4e0f-a188-f6cbb6e7d783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.akaverse.net/theakaverseappapi/wp-admin/media-upload.php?post_id=1041&amp;type=image&amp;TB_iframe=1&amp;width=753&amp;height=799</value>
      <webElementGuid>b0f574cf-bb82-4c67-9b55-d34fd271b034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>set-post-thumbnail</value>
      <webElementGuid>0eaa80d6-43fa-4dbf-8594-1b368f1f4023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thickbox</value>
      <webElementGuid>334d0851-1feb-46fe-8266-21011feaef07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Set featured image</value>
      <webElementGuid>53f317ea-4b74-46fd-b98f-ed82ececd0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;set-post-thumbnail&quot;)</value>
      <webElementGuid>df48bbe3-61cf-42c4-aa93-efef2049e09a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='set-post-thumbnail']</value>
      <webElementGuid>2232d471-307d-44d4-99d7-556903de2841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postimagediv']/div[2]/p/a</value>
      <webElementGuid>44fa364c-4cd7-479e-b87e-37825559e05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Set featured image')]</value>
      <webElementGuid>e4e00598-19b9-4239-bd51-69c56cac43cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle panel: Featured Image'])[1]/following::a[1]</value>
      <webElementGuid>99b320ef-79bc-4708-a05d-999864bae49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move down'])[1]/following::a[1]</value>
      <webElementGuid>11e3575d-d4ab-4584-99b6-75a170aa352b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages'])[2]/preceding::a[1]</value>
      <webElementGuid>227ef2f4-7210-4b0e-a571-44ccfd19bd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move up'])[2]/preceding::a[1]</value>
      <webElementGuid>ebf0fbc2-c8e4-4452-be8c-ffe353e63e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Set featured image']/parent::*</value>
      <webElementGuid>a87ba8e8-d0c9-4b21-b1ca-5fbbdaf6d23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.akaverse.net/theakaverseappapi/wp-admin/media-upload.php?post_id=1041&amp;type=image&amp;TB_iframe=1&amp;width=753&amp;height=799')]</value>
      <webElementGuid>a17f8f9b-1630-4050-81b7-032e7bf17525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>e236dfeb-7481-4a0d-8d9f-0b2a0732c57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.akaverse.net/theakaverseappapi/wp-admin/media-upload.php?post_id=1041&amp;type=image&amp;TB_iframe=1&amp;width=753&amp;height=799' and @id = 'set-post-thumbnail' and (text() = 'Set featured image' or . = 'Set featured image')]</value>
      <webElementGuid>dbf061c4-791a-43c7-a1db-c6ded9fe7440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
