<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>8e970254-dab0-4387-85ec-36b2aa7634f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__wp-uploader-id-3 > div.media-frame-toolbar > div.media-toolbar > div.media-toolbar-primary.search-form > button.button.media-button.button-primary.button-large.media-button-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[318]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92fc65d7-3299-47ae-bd7b-f590969dcec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6ce2bb9-30f7-45a5-93fe-b9699f6a932b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button media-button button-primary button-large media-button-select</value>
      <webElementGuid>c2976b33-dc3a-4642-b1f0-485536413bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>4e6c6ca4-fdea-4bd9-8a20-54247fe95693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__wp-uploader-id-3&quot;)/div[@class=&quot;media-frame-toolbar&quot;]/div[@class=&quot;media-toolbar&quot;]/div[@class=&quot;media-toolbar-primary search-form&quot;]/button[@class=&quot;button media-button button-primary button-large media-button-select&quot;]</value>
      <webElementGuid>d9083900-96b7-409a-a177-55c04f856dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[318]</value>
      <webElementGuid>696a49dd-6828-40ae-8d8e-d4a5006f871e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__wp-uploader-id-3']/div[4]/div/div[2]/button</value>
      <webElementGuid>64646417-ee6b-4bdf-a008-047fd4c1b2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected media actions'])[2]/following::button[1]</value>
      <webElementGuid>4103215c-f396-43f5-846a-2a8d31113a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy URL to clipboard'])[1]/following::button[1]</value>
      <webElementGuid>e7c79087-e54d-433e-9b59-3f4e74f9233a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop files to upload'])[6]/preceding::button[1]</value>
      <webElementGuid>aa0e4d05-0048-4460-be7e-2d3eadbff210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>dae289fb-e8e1-4d41-884c-ac83c0e76648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div/div[4]/div/div[2]/button</value>
      <webElementGuid>33c4a97b-ccac-4bb8-a708-2b06657ed722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>bf1cced5-6db6-4065-8f7c-65fc242fc0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
