<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Set featured image</name>
   <tag></tag>
   <elementGuidId>6d1bbd50-795e-4934-b3ae-b6607b8424df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.media-button.button-primary.button-large.media-button-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[228]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>937bb24b-e245-4146-9be8-8539f4083cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1dcc14a-5573-4440-8f27-6fd45497e024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button media-button button-primary button-large media-button-select</value>
      <webElementGuid>b4fbd85c-0deb-4d82-bcb3-b662f9a416a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Set featured image</value>
      <webElementGuid>602b9ddd-cf9c-4928-b58e-a60915e05219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__wp-uploader-id-0&quot;)/div[@class=&quot;media-frame-toolbar&quot;]/div[@class=&quot;media-toolbar&quot;]/div[@class=&quot;media-toolbar-primary search-form&quot;]/button[@class=&quot;button media-button button-primary button-large media-button-select&quot;]</value>
      <webElementGuid>120db159-2ce9-4714-910c-79e21ca033e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[228]</value>
      <webElementGuid>575c7893-9811-40ed-a05e-1689158c4e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__wp-uploader-id-0']/div[4]/div/div[2]/button</value>
      <webElementGuid>8793071a-b80b-41c1-8ad4-4bc18eabc196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected media actions'])[1]/following::button[1]</value>
      <webElementGuid>ac76e539-8cac-44a5-9412-358ca97f0353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy URL to clipboard'])[1]/following::button[1]</value>
      <webElementGuid>5f553ab3-8299-4186-b735-78699adf2fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop files to upload'])[4]/preceding::button[1]</value>
      <webElementGuid>a0f4eb1c-07e9-4cbd-a667-b209745ece02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button</value>
      <webElementGuid>52e28ea3-c6e9-477b-a431-1ea4be243b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Set featured image' or . = 'Set featured image')]</value>
      <webElementGuid>a03dbdad-9a36-4150-8dc3-568b6265aec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
