<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Deselect_thumbnail_1</name>
   <tag></tag>
   <elementGuidId>97235e9d-1972-4aac-a44f-c227d7d56672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__attachments-view-828 > li.attachment.save-ready > div.attachment-preview.js--select-attachment.type-image.subtype-png.landscape > div.thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='__attachments-view-828']/li[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>226f49da-2ae4-473d-9f88-126ef0491b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumbnail</value>
      <webElementGuid>a28a21ac-60c0-4082-8185-ef641ffdecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__attachments-view-828&quot;)/li[@class=&quot;attachment save-ready&quot;]/div[@class=&quot;attachment-preview js--select-attachment type-image subtype-png landscape&quot;]/div[@class=&quot;thumbnail&quot;]</value>
      <webElementGuid>849cdee0-c683-4688-b5d5-db1b49122081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='__attachments-view-828']/li[2]/div/div</value>
      <webElementGuid>a2133477-64b5-4c8b-beae-a01f4e99b216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect'])[81]/following::div[2]</value>
      <webElementGuid>8dd012d1-396f-474b-b31f-33994648a0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media list'])[2]/following::div[6]</value>
      <webElementGuid>ed17a822-1fe3-4f6b-886c-fd08cfdc4b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect'])[82]/preceding::div[2]</value>
      <webElementGuid>cad660f1-52d4-410b-ac9c-6039fceb30cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect'])[83]/preceding::div[5]</value>
      <webElementGuid>433e8e55-af33-4176-9c91-b1adfd5912c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/div[3]/div[2]/div/div[3]/ul/li[2]/div/div</value>
      <webElementGuid>1766cdc4-e012-487f-838f-72f4b1568f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
