<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>7d6ba1cc-c918-4728-94d1-a03ec9ed8cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__wp-uploader-id-6 > div.media-frame-toolbar > div.media-toolbar > div.media-toolbar-primary.search-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__wp-uploader-id-6']/div[4]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b59b9cd2-f661-4687-9a69-d91afc2bcf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-toolbar-primary search-form</value>
      <webElementGuid>0bddc572-88da-4711-aa5a-0e138e39ef82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>3b7ee611-ae65-4b4a-abcd-68f261733eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__wp-uploader-id-6&quot;)/div[@class=&quot;media-frame-toolbar&quot;]/div[@class=&quot;media-toolbar&quot;]/div[@class=&quot;media-toolbar-primary search-form&quot;]</value>
      <webElementGuid>a58687b7-0cdc-4f86-b02b-0195c9af0b94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__wp-uploader-id-6']/div[4]/div/div[2]</value>
      <webElementGuid>220adf41-6aa8-489f-a977-b854f5a8443d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected media actions'])[2]/following::div[4]</value>
      <webElementGuid>93381e55-ec23-4c78-8d37-a94e6d79dbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy URL to clipboard'])[1]/following::div[4]</value>
      <webElementGuid>e7788b2c-3f3e-4929-87e2-8f315b945165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop files to upload'])[6]/preceding::div[1]</value>
      <webElementGuid>9e2e69ac-f265-4cd8-a243-26c518bd4c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/div[4]/div/div[2]</value>
      <webElementGuid>fe0ead43-da46-4078-b00a-416938183398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>e126b54b-095b-428a-a5f3-423164115a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
