<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Georgia_content_ifr</name>
   <tag></tag>
   <elementGuidId>5690ce88-4985-4f1a-ae7e-96bbff7764db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='content_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e183502a-7f0d-44e5-b710-8471280358d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content_ifr</value>
      <webElementGuid>c0377002-cf0b-45ba-bb20-1a583e5522d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a3c325e-5d42-4a78-9650-bf4d368ec7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e52c3daa-499d-43e1-8a84-135f6d5bc346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area. Press Alt-Shift-H for help.</value>
      <webElementGuid>016bb676-6e0e-4efb-a6cd-f541840b38ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_ifr&quot;)</value>
      <webElementGuid>3e902dbf-9612-48f1-aadc-26b031e1476a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='content_ifr']</value>
      <webElementGuid>3400adec-fc3a-4a9a-a5a2-371a5d4d7dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mceu_41']/iframe</value>
      <webElementGuid>e2562a40-6c28-491f-b8ef-b47674f479d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>514639e9-bfd6-4252-90f0-d4e6098963d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'content_ifr' and @title = 'Rich Text Area. Press Alt-Shift-H for help.']</value>
      <webElementGuid>95441702-8860-4f40-8bc0-c6c72cdd7272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
