<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember Me_wp-submit</name>
   <tag></tag>
   <elementGuidId>d63b86f1-9a72-4c73-b5b8-53c47b5986aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wp-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f2e5ad3-1efa-495b-b332-e691f65c7068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>47085e5f-d401-4ba6-aed5-d6c58bdf6d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wp-submit</value>
      <webElementGuid>6bd0bfe7-4b62-4dca-bfff-8158422dfd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-submit</value>
      <webElementGuid>c817c3eb-740f-44d5-9633-01ee111e6a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-primary button-large</value>
      <webElementGuid>66eaccc2-c898-4ba6-b633-4e6b588c46a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>c2cfb700-0801-41e3-98d7-1cb9f640dbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-submit&quot;)</value>
      <webElementGuid>142a9db4-8af6-4f2f-9bce-0c9a98bbdb67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-submit']</value>
      <webElementGuid>8adf5322-aad3-4c58-88ec-05eaf7b8c26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/p[3]/input</value>
      <webElementGuid>a7ec9063-0034-4cdc-8fd6-a67721761c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>7cd6cae2-6697-4bf2-a69c-5d6d276fa854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'wp-submit' and @id = 'wp-submit']</value>
      <webElementGuid>de250546-1074-4d01-bf99-c870f42620d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
