<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember Me_wp-submit</name>
   <tag></tag>
   <elementGuidId>d63b86f1-9a72-4c73-b5b8-53c47b5986aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wp-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>244b64ba-a860-4122-8910-d377d137a1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>74e008e0-9390-490e-a89f-41d5ddbe0e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wp-submit</value>
      <webElementGuid>a87c61be-c76a-4812-9261-20e99ed66ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-submit</value>
      <webElementGuid>00ce6297-d32c-4500-9ec4-fea72c8aaf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-primary button-large</value>
      <webElementGuid>2d9d5108-89ae-4187-9fb0-94b3e5b261a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>05a24895-13f3-4f08-8a4a-1cbafab5a5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-submit&quot;)</value>
      <webElementGuid>76c293ba-3af3-401d-ad55-e259e959e435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-submit']</value>
      <webElementGuid>e5fc52af-3c31-48c0-ae9d-3b2cb0c908c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/p[3]/input</value>
      <webElementGuid>34751dfd-972a-42b8-ac4f-aea25cbf9bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>500aa315-8138-46b1-bd96-16588a417fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'wp-submit' and @id = 'wp-submit']</value>
      <webElementGuid>7adf96cc-264b-4806-a97f-bec154d9bab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
